export { addresses } from "@/@types/addresses";
export { cardsData } from "@/@types/cardsData";
export { contacts } from "@/@types/contacts";
export { handleScroll } from "@/@types/handleScroll";
export { scrollToTop } from "@/@types/scrollToTop";
export { shortDescription } from "@/@types/shortDescription";
export { socialLinks } from "@/@types/socialLinks";
export { spanHandleClick } from "@/@types/spanHandleClick";
export { default as CopyRight } from "@/components/CopyRight/CopyRight";
export { default as MainItens } from "@/components/MainItens/MainItens";
export { default as NavBar } from "@/components/NavBar/NavBar";
export { default as SectionCards } from "@/components/SectionCards/SectionCards";
export { default as SectionContacts } from "@/components/SectionContacts/SectionContacts";
export { default as SectionMain } from "@/components/SectionMain/SectionMain";
export { copyToClipBoard } from "@/functions/copyToClipBoard";
export { useClickOutside } from "@/hooks/useClickOutSide";
export { CardStateProvider } from "@/providers/CardStateProvider";
export { default as MenuManager } from "@/providers/MenuManager";
export { default as FooterFAQ } from "@/ui/CopyRight/FooterFAQ";
export { default as SocialMedia } from "@/ui/MainItens/SocialMedia";
export { default as TopClick } from "@/ui/MainItens/TopClick";
export { default as Logo } from "@/ui/NavBar/Logo";
export { default as MenuClose } from "@/ui/NavBar/MenuClose";
export { default as MenuOpen } from "@/ui/NavBar/MenuOpen";
export { default as AnimatedCards } from "@/ui/SectionCards/AnimatedCards";
export { default as ShowAll } from "@/ui/SectionCards/ShowAll";
export { default as TextCards } from "@/ui/SectionCards/TextCards";
export { default as Address } from "@/ui/SectionContacts/Address";
export { default as AllContacts } from "@/ui/SectionContacts/AllContacts";
export { default as Contacts } from "@/ui/SectionContacts/Contacts";
export { default as Map } from "@/ui/SectionContacts/Map";
export { default as ImageRafa } from "@/ui/SectionMain/ImageRafa";
export { default as TextMain } from "@/ui/SectionMain/TextMain";

